#!/bin/sh

# see http://0pointer.de/blog/projects/os-release and https://www.freedesktop.org/software/systemd/man/os-release.html
test -e /etc/os-release && os_release='/etc/os-release' || os_release='/usr/lib/os-release'
. "${os_release}"

k=$(uname -srmo)
e=$(curl -s checkip.amazonaws.com)
h=$(hostname -f)
a=$(hostname -a)
i=$(hostname -I | cut -d " " -f 1)
d=$(df -h  | grep /$   | awk {'print "total " $2 "	free " $4 "	used " $3 " (" $5 ")"'})
m=$(free -h | grep Mem | awk {'print "total " $2 "	free " $7 "	used " $3'})
u=$(uptime -p | cut -c 4-)

cpu=$(cut -c 1,2 /sys/class/thermal/thermal_zone0/temp)
gpu=$(vcgencmd measure_temp | cut -c 7,6)
t="CPU ${cpu}° C	GPU ${gpu}° C"

BL='\033[1;34m'
BG='\033[1;31m'
BR='\033[0;33m'
CY='\033[1;36m'
DG='\033[1;30m'
LR='\033[1;32m'
NG='\033[0;32m'
NR='\033[0;31m'
PU='\033[1;35m'
RS='\033[0m'
YE='\033[1;33m'

echo "
$BR  .==$BR==============$BR==.  $RS
$BR  | .$BR--------------$BR. |  $NG $PRETTY_NAME - $k
$BR  | |$CY--.__.--.__.--$BR| |  $RS
$BR  | |$PU--.__.--.__.--$BR| |  $NR hostnames.......: $LR$h$BR and $BG$a 
$BR  | |$CY--.__.--.__.--$BR| |  $NR addresses.......: $CY$i$NR$BR and $PU$e 
$BR  | |$PU--.__.--.__.--$BR| |  $NR disk............: $BL$d
$BR  | |$CY--.__.--.__.--$BR| |  $NR memory..........: $BL$m
$BR  | '$BR--------------$BR' |  $NR temperature ....: $YE$t
$BR  |  $DG##    ()    ##$BR  |  $NR uptime..........: $PU$u
$BR  '==$BR==============$BR=='  $RS
"
