#!/bin/sh

h=$(hostname)

echo "
                    ROBCO INDUSTRIES UNIFIED OPERATING SYSTEM
                      COPYRIGHT 2075-2077 ROBCO INDUSTRIES

                                - $h -
-------------------------------------------------------------------------------
"