#!/bin/sh
export TERM=xterm-256color
r=$(lsb_release -sd)
k=$(uname -srmo)
e=$(wget -q -O - http://ipv4.icanhazip.com/ | tail)
h=$(hostname -f)
a=$(hostname -a)
i=$(hostname -I | cut -d " " -f 1)
d=$(df -h  | grep root | awk {'print "total " $2 "	free " $4 "	used " $3 " (" $5 ")"'})
m=$(free -h | grep Mem | awk {'print "total " $2 "	free " $7 "	used " $3'})
u=$(uptime -p | sed s/up.//)

cpu=$(cut -c 1,2 /sys/class/thermal/thermal_zone0/temp)
gpu=$(/opt/vc/bin/vcgencmd measure_temp | cut -c 7,6)
t="CPU ${cpu}° C	GPU ${gpu}° C"

BG='\033[1;32m'
BR='\033[1;31m'
BL='\033[1;34m'
CY='\033[1;36m'
NG='\033[0;32m'
NR='\033[0;31m'
OR='\033[0;33m'
PU='\033[1;35m'
RS='\033[0m'
YE='\033[1;33m'

echo "
$NG      .~~.   .~~.       $RS
$NG     '. \ ' ' / .'      $BG $r - $k
$NR      .~ .~~~..~.       $RS
$NR     : .~.'~'.~. :      $BR hostnames.......: $NR$h$BR and $NG$a
$NR    ~ (   ) (   ) ~     $BR addresses.......: $CY$i$NR$BR and $OR$e
$NR   ( : '~'.~.'~' : )    $BR disk............: $PU$d
$NR    ~ .~ (   ) ~. ~     $BR memory..........: $PU$m
$NR     (  : '~' :  )      $BR temperature.....: $YE$t
$NR      '~ .~~~. ~'       $BR uptime..........: $BL$u
$NR          '~'           $RS
"
